package.json, src/components/PageFooter/PageFooter.js, src/components/PageHeader/PageHeader.js, src/locales/en-us.json, src/locales/zh-cn.json, yarn.lock
Add `docs`  link to documentation site and some other minor fixes.
=> Add docs link

src/locales/en-us.json, src/locales/zh-cn.json
https://github.com/darwinia-network/docs/issues/239
=> fix: abount docs home page link

src/page/Plo/FourCards/index.js, src/page/PloContribute/gql.js, src/page/PloContribute/index.js
=> plo issue fix

src/page/PloContribute/index.js, src/page/PloContribute/styles.module.scss
=> Jay plo op

src/page/Plo/Welcome/index.js, src/page/PloContribute/gql.js, src/page/PloContribute/index.js, src/page/PloContribute/styles.module.scss, src/page/PloContribute/useEcharts.js, src/page/PloContribute/utils.js
=> Jay plo issue

src/page/PloContribute/index.js
=> Jay plo issue fix

src/page/Home/index.js, src/page/PloContribute/index.js, src/page/PloContribute/styles.module.scss
=> Jay plo dev op

src/page/PloContribute/index.js, src/page/PloContribute/styles.module.scss
=> Jay plo fix

src/page/PloContribute/gql.js, src/page/PloContribute/index.js
fix #246 
等 https://project.subquery.network/project/darwinia-network/home-plo-polkadot 同步完
=> reward stage 2

src/page/Plo/Timeline/index.js, src/page/PloContribute/components/btc-reward.js, src/page/PloContribute/styles.module.scss, src/page/PloContribute/top5.json
1. https://github.com/darwinia-network/home/issues/250
2. https://github.com/darwinia-network/home/issues/249
=> Update timeline and btc reward

.github/workflows/deploy-dev.yml, .github/workflows/deploy-prd.yml, .github/workflows/deploy-stg.yml
https://github.com/darwinia-network/crab-docs/pull/111
=> Vercel action

src/page/PloContribute/components/metaverse-nft.js
https://project.subquery.network/project/darwinia-network/darwinia-nft-polkadot
=> chore: update nft remark subql endpoint

src/page/Blog/data.js
Add Monthly Dispatch for April
=> add monthly Dispatch

public/manifest.json, src/assets/styles/index.scss, src/components/Footer/index.tsx, src/locale/localeKeys.ts, src/locale/translations/enUS.ts, src/utils/index.ts
-email subscription user experience improvement
=> Email subcription improvement

src/data/menu.tsx
=> added nav link

src/data/menu.tsx, src/locale/localeKeys.ts, src/locale/translations/enUS.ts, src/pages/PageNotFound/index.tsx
-minor ui updates
-added support link
=> minor ui updates

src/data/menu.tsx, src/locale/localeKeys.ts, src/locale/translations/enUS.ts
=> links updated

.github/workflows/deploy-dev.yml, .github/workflows/deploy-prd.yml, .github/workflows/deploy-stg.yml, src/data/menu.tsx, src/utils/darwiniaModelAnimation.tsx
Added crab subview explorer link
=> Link update

src/components/Feature/index.tsx, src/components/FeatureWrapper/index.tsx, src/components/Navigation/index.tsx, src/data/developers.tsx, src/data/footer.tsx, src/data/home.tsx, src/data/menu.tsx, src/data/types.tsx, src/locale/localeKeys.ts, src/locale/translations/enUS.ts
=> link updates

src/components/Navigation/index.tsx, src/data/menu.tsx, src/locale/translations/enUS.ts
-Added new links and changed the links order
=> Darwinia 2.0 going live preparations

src/components/Navigation/index.tsx, src/data/community.tsx, src/data/developers.tsx, src/data/footer.tsx, src/data/home.tsx, src/data/menu.tsx, src/data/tokens.tsx, src/locale/localeKeys.ts, src/locale/translations/enUS.ts
=> docs links updates

src/data/developers.tsx, src/locale/localeKeys.ts, src/locale/translations/enUS.ts
=> Remove JS-SDK-API

src/components/ring/DecentralizedExchanges.tsx
This PR closes https://github.com/darwinia-network/home/issues/392
=> Added Space before CoinGecko in DEX section

src/components/Header/data.ts
=> Update data.ts correct bridge link

src/components/ring/RingCards.tsx, src/data/ringdata.ts
Fixes https://github.com/darwinia-network/home/issues/391
~Partially~ fixes: https://github.com/darwinia-network/home/issues/393
~TODO for next PR: Add trading pair links.~
Done!
=> Fixes Minor Usability issues and adds links to exchange

src/layouts/HomePageDesktopLayout.tsx
Fixes #404 @wuminzhe can you please check if your issue is solved on this branch, I don't have a mac so I not able to test properly.
=> Fixes Mac's Scroll Problem.

package-lock.json, package.json, src/assets/styles/index.scss, src/pages/GetRing/index.tsx
related:
- https://github.com/ringecosystem/integration/issues/18
- https://github.com/ringecosystem/integration/issues/17
=> Try to Add Cow Widget
